# Default values for performance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/mojaloop-prod/tiger-beetle
  tag: latest
  pullPolicy: Always

replicaCount: 1

containers:
  api:
    service:
      ports:
        api:
          name: api
          externalPort: 30000
          internalPort: 30000
        admin:
          name: admin
          externalPort: 81
          internalPort: 2222

service:
  type: ClusterIP

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: '/'
  hosts:
    api:
      host: tb.perf.openafrica.network
      port: 80
    admin:
      host: tb-admin.perf.openafrica.network
      port: 81

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations:
  - key: "node-role.mojaloop.io"
    operator: "Equal"
    value: "ml_cl_position"
    effect: "NoSchedule"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "node-role.mojaloop.io"
              operator: In
              values: [ "ml_cl_position" ]
