apiVersion: v1
kind: Service
metadata:
  name: {{ include "tigerbeetle.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "tigerbeetle.name" . }}
    helm.sh/chart: {{ include "tigerbeetle.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $port := .Values.containers.api.service.ports }}
    - port: {{ $port.externalPort }}
      targetPort: {{ $port.internalPort }}
      protocol: TCP
      name: {{ $port.name }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "tigerbeetle.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
